service: spamouts-slack-autodeletion
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment: ${file(./env.${opt:stage, 'dev'}.json)}
  memorySize: 128
  timeout: 35
  

functions:
  # Use UTC in schedule
  cleanAntispamers:
    handler: src/index.cleanAntispamersChannel
    events:
      - schedule:
          rate: cron(0/2 3-20,21,22,23 ? * MON-FRI *)
  cleanModerators:
    handler: src/index.cleanModeratorsChannel
    events:
      - schedule:
          rate: cron(0/5 3-20,21,22 ? * MON-FRI *)

plugins:
  - serverless-esbuild
custom:
  esbuild:
    plugins: esbuild-plugins.js